### ISSUE TITLE
Templatizar diretiva jd-panel

### ISSUE THREAD

**Issue by fabioviana** [jediproject/ng-jedi-layout#2]
Atualmente o panel possui várias constantes que compõem o html final, esse comportamento deve ser melhorado para ser como a diretiva jd-input, utilizando um arquivo template único.

**Comment by hsbrighenti** [comment]
Closed by commits e7b12b8dbb56454088d265010fcd1be105e24e09 and 87c9c452df7b279a59b2e2f5b54d1251eb686747
