### ISSUE TITLE
Enter triggering incorrect button

### ISSUE THREAD

**Issue by Tanato** [jediproject/ng-jedi-layout#5]
When a enter is pressed in a jd-input alone, it trigger the first button that are in the page, instead of doing nothing when a jd-input is alone.

This behavior occur probably because of the modal jd-input with a button to open a select modal.

**Comment by hsbrighenti** [comment]
I'm on it

**Comment by hsbrighenti** [comment]
That's actually standard behaviour of form elements in AngularJs. And can be avoided by explictly using `type="button"` on button elements.

From the [AngularJs docs](https://docs.angularjs.org/api/ng/directive/form):

> This is because of the following form submission rules in the HTML specification:
> 
> If a form has only one input field then hitting enter in this field triggers form submit (ngSubmit)
> if a form has 2+ input fields and no buttons or input[type=submit] then hitting enter doesn't trigger submit
> if a form has one or more input fields and one or more buttons or input[type=submit] then hitting enter in any of the input fields will trigger the click handler on the first button or input[type=submit](ngClick) and a submit handler on the enclosing form (ngSubmit)
